// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var MySql2 = require("bs-mysql2/src/MySql2.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");
var MyRequest$MyNewProject = require("./MyRequest.bs.js");

var connection = {
  contents: MySql2.Connection.connect("127.0.0.1", 3306, "root", undefined, undefined, undefined)
};

var con = connection.contents;

function showDataBases(param) {
  return MySql2.execute(con, "SHOW DATABASES", undefined, (function (res) {
                var variant = res.NAME;
                if (variant === "Select") {
                  console.log("SELECT: ", res.VAL);
                } else if (variant === "Mutation") {
                  console.log("MUTATION: ", res.VAL);
                } else {
                  console.log("ERROR: ", res.VAL);
                }
                
              }));
}

function createDatabase(param) {
  return MySql2.execute(con, "CREATE DATABASE IF NOT EXISTS reason_ml", undefined, (function (res) {
                if (typeof res === "string" || res.NAME !== "Error") {
                  console.log("[DATABASE] CREATED DATABASE reason_ml");
                } else {
                  console.log("ERROR: ", res.VAL);
                }
                
              }));
}

function changeConnectionToDatabase(param) {
  connection.contents = MySql2.Connection.connect("127.0.0.1", 3306, "root", "", "reason_ml", undefined);
  console.log("[DATABASE] NEW CONNECTION STATUS, CHANGE TO reason_ml DATABASE");
  
}

function createAdminAccountsTable(param) {
  return MySql2.execute(connection.contents, "CREATE TABLE admin_accounts (\n        id int(11) NOT NULL AUTO_INCREMENT,\n        username varchar(255) NOT NULL,\n        password varchar(512) NOT NULL,\n        PRIMARY KEY(id)\n    )", undefined, (function (res) {
                if (typeof res === "string" || res.NAME !== "Error") {
                  console.log("[DATABASE] CREATED TABLE admin_accounts");
                } else {
                  console.log("ERROR: ", res.VAL);
                }
                
              }));
}

function createAdminAccount(username, password) {
  var named = MySql2.Params.named(Json_encode.object_({
            hd: [
              "username",
              username
            ],
            tl: {
              hd: [
                "password",
                password
              ],
              tl: /* [] */0
            }
          }));
  var register = function (value) {
    var stringify_value = JSON.stringify(value);
    console.log(stringify_value);
    var match = stringify_value === "true";
    if (match) {
      throw {
            RE_EXN_ID: "Match_failure",
            _1: [
              "Database.re",
              56,
              8
            ],
            Error: new Error()
          };
    }
    return MySql2.execute(connection.contents, "INSERT INTO admin_accounts (username, password) VALUES(:username, :password)", Caml_option.some(named), (function (res) {
                  console.log(res);
                  
                }));
  };
  var username_string = JSON.stringify(username);
  var req = MyRequest$MyNewProject.checkIfExistAdminUser(username_string);
  req.then(function (json) {
        return Promise.resolve(register(json));
      });
  
}

exports.connection = connection;
exports.con = con;
exports.showDataBases = showDataBases;
exports.createDatabase = createDatabase;
exports.changeConnectionToDatabase = changeConnectionToDatabase;
exports.createAdminAccountsTable = createAdminAccountsTable;
exports.createAdminAccount = createAdminAccount;
/* connection Not a pure module */
