// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var MySql2 = require("bs-mysql2/src/MySql2.bs.js");

var connection = {
  contents: MySql2.Connection.connect("127.0.0.1", 3306, "root", undefined, undefined, undefined)
};

var con = connection.contents;

function showDataBases(param) {
  return MySql2.execute(con, "SHOW DATABASES", undefined, (function (res) {
                var variant = res.NAME;
                if (variant === "Select") {
                  console.log("SELECT: ", res.VAL);
                } else if (variant === "Mutation") {
                  console.log("MUTATION: ", res.VAL);
                } else {
                  console.log("ERROR: ", res.VAL);
                }
                
              }));
}

function createDatabase(param) {
  return MySql2.execute(con, "CREATE DATABASE IF NOT EXISTS reason_ml", undefined, (function (res) {
                if (typeof res === "string" || res.NAME !== "Error") {
                  console.log("[DATABASE] CREATED DATABASE reason_ml");
                } else {
                  console.log("ERROR: ", res.VAL);
                }
                
              }));
}

function changeConnectionToDatabase(param) {
  connection.contents = MySql2.Connection.connect("127.0.0.1", 3306, "root", "", "reason_ml", undefined);
  console.log("[DATABASE] NEW CONNECTION STATUS, CHANGE TO reason_ml DATABASE");
  
}

function createAdminAccountsTable(param) {
  return MySql2.execute(connection.contents, "CREATE TABLE admin_accounts (\n        id int(11) NOT NULL AUTO_INCREMENT,\n        username varchar(255) NOT NULL,\n        password varchar(512) NOT NULL,\n        PRIMARY KEY(id)\n    )", undefined, (function (res) {
                if (typeof res === "string" || res.NAME !== "Error") {
                  console.log("[DATABASE] CREATED TABLE admin_accounts");
                } else {
                  console.log("ERROR: ", res.VAL);
                }
                
              }));
}

function createAdminAccount(username, password) {
  var sql = "INSERT INTO admin_accounts (username, value) VALUES('" + (username + ("','" + (password + "')")));
  var partial_arg = connection.contents;
  return function (param) {
    return MySql2.execute(partial_arg, sql, undefined, param);
  };
}

exports.connection = connection;
exports.con = con;
exports.showDataBases = showDataBases;
exports.createDatabase = createDatabase;
exports.changeConnectionToDatabase = changeConnectionToDatabase;
exports.createAdminAccountsTable = createAdminAccountsTable;
exports.createAdminAccount = createAdminAccount;
/* connection Not a pure module */
