// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var MySql2 = require("bs-mysql2/src/MySql2.bs.js");

var connection = {
  contents: MySql2.Connection.connect("127.0.0.1", 3306, "root", undefined, undefined, undefined)
};

var con = connection.contents;

function showDataBases(param) {
  return MySql2.execute(con, "SHOW DATABASES", undefined, (function (res) {
                var variant = res.NAME;
                if (variant === "Select") {
                  console.log("SELECT: ", res.VAL);
                } else if (variant === "Mutation") {
                  console.log("MUTATION: ", res.VAL);
                } else {
                  console.log("ERROR: ", res.VAL);
                }
                
              }));
}

function createDatabase(param) {
  return MySql2.execute(con, "CREATE DATABASE IF NOT EXISTS reason_ml", undefined, (function (res) {
                if (typeof res === "string" || res.NAME !== "Error") {
                  console.log("[DATABASE] CREATED DATABASE reason_ml");
                } else {
                  console.log("ERROR: ", res.VAL);
                }
                
              }));
}

function changeConnectionToDatabase(param) {
  connection.contents = MySql2.Connection.connect("127.0.0.1", 3306, "root", "", "reason_ml", undefined);
  console.log("[DATABASE] NEW CONNECTION STATUS, CHANGE TO reason_ml DATABASE");
  
}

exports.connection = connection;
exports.con = con;
exports.showDataBases = showDataBases;
exports.createDatabase = createDatabase;
exports.changeConnectionToDatabase = changeConnectionToDatabase;
/* connection Not a pure module */
