// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Express = require("bs-express/src/Express.bs.js");
var Process = require("process");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");

var app = Express.express(undefined);

var stringServerPort = "30120";

function onListen(e) {
  var val;
  try {
    val = e;
  }
  catch (raw_e){
    var e$1 = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e$1.RE_EXN_ID === Js_exn.$$Error) {
      console.log(e$1._1);
      return Process.exit(1);
    }
    throw e$1;
  }
  console.log("Listening at http://127.0.0.1:30120");
  
}

function makeSuccessJson(param) {
  var json = {};
  json["success"] = "Hello World!";
  return json;
}

Express.App.get(app, "/reason", Express.Middleware.from(function (next, req) {
          var partial_arg = makeSuccessJson(undefined);
          return function (param) {
            return Express.$$Response.sendJson(partial_arg, param);
          };
        }));

Express.App.get(app, "/hello", Express.Middleware.from(function (next, req) {
          var myjson = function (param) {
            var json = {};
            json["success"] = "Hello World!";
            return json;
          };
          var partial_arg = myjson(undefined);
          return function (param) {
            return Express.$$Response.sendJson(partial_arg, param);
          };
        }));

var server = Express.App.listen(app, 30120, undefined, onListen, undefined);

var serverPORT = 30120;

exports.app = app;
exports.serverPORT = serverPORT;
exports.stringServerPort = stringServerPort;
exports.onListen = onListen;
exports.makeSuccessJson = makeSuccessJson;
exports.server = server;
/* app Not a pure module */
